
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


# Example configuration.yaml entry

input_text:
  text1:
    name: Input EC Value. Example "cal:40"
    initial: Enter EC Calibration Value 
  text2:
    name: Input pH Value (pH4:pH7)
    initial: Enter pH Calibration Value
  text3:
    name: Set MotorSpeed (0-255). 255= max speed 100% 
    initial: Enter Speed Value
  text4:
    name: Text 4
    mode: password
    

mqtt:
  switch:
    - name: arduino builin led
      state_topic: "esp/test"
      command_topic: "esp/test"
      payload_on: "#on"
      payload_off: "#off"
      state_on: "#on"
      state_off: "#off"
      retain: false
    #Relay Board and L-298N Board
    # MQTT (4 CHANNEL RELAY BOARD IN CONTROL BOX)
    # - For all of the relay board and outlet mqtt switches below, the payload_on and
    #   payload_off will be 2 digits. The first is which relay (0 = first relay on the board)
    #   and the second will be a 1 if its being turned on and a 0 if being turned off.
    # - The ESP32 is programmed to send feedback for the relays and follows the same scheme,
    #   so state_on and state_off will be the same as the payload on/off.
    - name: "Motor1"               #L-298N Board (motor driver)
      state_topic: "feedback/relays"
      command_topic: "control/relays"
      payload_on: "0:0:1"                 #Format is <BOARD#><RELAY#><STATE>
      payload_off: "0:0:0"                #For Motor driver High(1) is on and LOW(0) is off
      state_on: "0:0:1"                   #"0:0:1" = (Board0)(Motor0)(ON)
      state_off: "0:0:0"                  #"0:0:0" = (Board0)(Motor0)(OFF)
    - name: "Motor2"
      state_topic: "feedback/relays"
      command_topic: "control/relays"
      payload_on: "0:1:1"
      payload_off: "0:1:0"
      state_on: "0:1:1"
      state_off: "0:1:0"
    - name: "Motor3"
      state_topic: "feedback/relays"
      command_topic: "control/relays"
      payload_on: "0:2:1"
      payload_off: "0:2:0"
      state_on: "0:2:1"
      state_off: "0:2:0"
      
    - name: "Relay4CH 0"                    #Relay Board2
      state_topic: "feedback/relays"
      command_topic: "control/relays"
      payload_on: "1:0:0"                   #Format is <BOARD#><RELAY#><STATE>
      payload_off: "1:0:1"                  #for Relay High(1) is off and Low(0) is on 
      state_on: "1:0:0"                     #"1:0:0" = (Board1)(Relay0)(ON)            
      state_off: "1:0:1"                    #"1:0:1" = (Board1)(Relay0)(OFF)
    - name: "Relay4CH 1"
      state_topic: "feedback/relays"
      command_topic: "control/relays"
      payload_on: "1:1:0"
      payload_off: "1:1:1"
      state_on: "1:1:0"
      state_off: "1:1:1"        
    - name: "Relay4CH 2"
      state_topic: "feedback/relays"
      command_topic: "control/relays"
      payload_on: "1:2:0"
      payload_off: "1:2:1"
      state_on: "1:2:0"
      state_off: "1:2:1"              
    - name: "Relay4CH 3"
      state_topic: "feedback/relays"
      command_topic: "control/relays"
      payload_on: "1:3:0"
      payload_off: "1:3:1"
      state_on: "1:3:0"
      state_off: "1:3:1"  
      
    #EC and pH Calibration button
    - name: "ECcalibrationButton"
      state_topic: "feedback/ECbutton"
      command_topic: "calibrate/ECbutton"
      payload_on: "High"                     #High is turn on  
      payload_off: "Low"                     #Low is turn off 
      state_on: "on"                         #feedback "on to know it receive 
      state_off: "off"                       #feedback "off to know it receive 
    - name: "pHcalibrationButton"
      state_topic: "feedback/pHbutton"
      command_topic: "calibrate/pHbutton"
      payload_on: "High"                     #High is turn on  
      payload_off: "Low"                     #Low is turn off 
      state_on: "on"                         #feedback "on to know it receive 
      state_off: "off"                       #feedback "off to know it receive 
     
      

  sensor:
    - name: "WaterTemperature"
      state_topic: "feedback/waterTemp"
      icon: mdi:thermometer
    # Volume Flow Rate
    - name: "FlowRate"
      state_topic: "feedback/flowRate"
      icon: mdi:waves-arrow-right
    # Water Level 
    - name: "WaterLevel"
      state_topic: "feedback/waterLevel"
      icon: mdi:waves-arrow-right
    # EC Value 
    - name: "TDSvalue"             #EC = TDS value * 2
      state_topic: "feedback/EC"
    - name: "ECvalue"             #EC = TDS value * 2
      state_topic: "feedback/EC"
      value_template: "{{ value | multiply(2) | round(2) }}" 
    # PH Value 
    - name: "PHvalue"
      state_topic: "feedback/PH"
    # PH Calibration Value 
    - name: "pHcalibrationValue"
      state_topic: "feedback/PHCalibration"
    # Debug
    - name: Debug
      state_topic: "feedback/debug"
    # Debug EC
    - name: DebugCalibration
      state_topic: "feedback/calibration"
    # MotorSpeed
    - name: MotorSpeed 
      state_topic: "feedback/motorspeed"
      
     
